//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sklepvisualstudio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SKLEPEntitiesNew : DbContext
    {
        public SKLEPEntitiesNew()
            : base("name=SKLEPEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drukarki> Drukarki { get; set; }
        public virtual DbSet<Laptop> Laptop { get; set; }
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
    }
}
